Update validation.py
It arises an error (ImportError: cannot import name 'compare_ssim' from 'skimage.measure') while running "validation.py". The error is because of the fact skimage.measure.compare_ssim has been removed in skimage 0.18.

To fix the issue, a line in the code in respective file needs to be changed from "from skimage.measure import compare_ssim, compare_psnr" to "from skimage.metrics import structural_similarity".